title: Hashgraph Developers
email: developers@hashgraph.com
description: >-
  Hashgraph devs unite! Get your SDK, study the tutorials,
  scour the docs. Become the hashgraph master.
baseurl: ""
url: "https://hashgraph.github.io"
timezone: America/Los_Angeles
twitter_username: hashgraph
github_username:  hashgraph
permalink: none
markdown: kramdown
plugins:
  - jekyll-feed
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
sass:
  style: compressed
  sass_dir: _sass
exclude:
- ".gitignore"
- CNAME
- readme.md
- _js/node_modules
